# Generated by Django 3.1.13 on 2021-10-10 19:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0077_auto_20211010_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 10, 19, 37, 23, 796044, tzinfo=utc)),
        ),
    ]
